#!/usr/bin/env bash
# debugging #2 - task 1
pkill -f apache2
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod o+rwx /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/"
sudo -u nginx service nginx start 
